declare const mergeButtonSelector = ".mr-widget-body.media button.btn.btn-success.btn-sm";
declare const statusIconSelector = ".mr-widget-body.media span.ci-status-icon.ci-status-icon-success";
declare const authorSelector = ".author-link";
declare const profileSelector = ".profile-link";
declare const downVotesSelector = "gl-emoji[data-name=\"thumbsdown\"] + span.award-control-text.js-counter";
declare const upVotesSelector = "gl-emoji[data-name=\"thumbsup\"] + span.award-control-text.js-counter";
declare const successStatusClasses: string[];
declare const warningStatusClasses: string[];
declare const acceptMergeClass = "accept-merge-request";
declare const disabledMergeClass = "js-disabled-merge-button";
declare const DISABLED = "disabled";
declare const SELF = "you";
declare const GITLAB = "GitLab";
declare const COMMA_SPACE = ", ";
declare const MERGE_REQUEST_PATH: RegExp;
declare const MIN_APPROVALS = 2;
declare const CHANGES_REQUESTED_MSG = "Some reviewers requested changes. Please address those.";
declare const APPROVALS_REQUIRED_MSG = "Requires 2 or more approvals.";
declare const debugging = false;
declare const log: (...args: any) => boolean | void;
declare function authorVote(voters: string, mrAuthor: string): boolean;
declare function getVotes(votesSelector: string, mrAuthor: string): number;
declare function disableMergeButton(mergeButton: HTMLButtonElement, message: string): void;
